CREATE DATABASE IF NOT EXISTS birdierigg;
ALTER DATABASE birdierigg CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE birdierigg;

CREATE TABLE IF NOT EXISTS dates (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS crew (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    nickname VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(100) NOT NULL UNIQUE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    category_id INT NOT NULL,
    date_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    responsible_id INT NOT NULL,
    required_amount INT NOT NULL DEFAULT 0,
    in_progress BOOLEAN NOT NULL DEFAULT FALSE,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (date_id) REFERENCES dates (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (responsible_id) REFERENCES crew (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS assignments (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE,
    task_id INT NOT NULL,
    crew_id INT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks (id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (crew_id) REFERENCES crew (id) ON UPDATE CASCADE ON DELETE CASCADE
);